cora:
  lr: 0.001
  lr_f: 0.01
  save_model: True
  num_hidden: 512
  num_heads: 4
  num_layers: 2
  weight_decay: 2e-4
  weight_decay_f: 1e-4
  max_epoch: 1750
  max_epoch_f: 300
  mask_rate: 0.5
  N_coms: 4
  use_mlp: True
  loss_z: 1
  combine_type: concat
  encoder: gat
  decoder: gat
  activation: prelu
  in_drop: 0.2
  attn_drop: 0.1
  linear_prob: True
  loss_fn: sce 
  drop_edge_rate: 0.0
  optimizer: adam
  replace_rate: 0.05 
  alpha_l: 3
  scheduler: True
citeseer:
  lr: 0.0005 #0.0005  # loss = loss + 3 * self.criterion(x_mlp, x)
  lr_f: 0.01
  save_model: True
  num_hidden: 512
  num_heads: 4
  num_layers: 2
  weight_decay: 3e-6 #3e-6
  weight_decay_f: 0.01
  max_epoch: 200
  max_epoch_f: 300
  mask_rate: 0.5
  N_coms: 4
  use_mlp: True
  loss_z: 2
  combine_type: concat
  encoder: gat
  decoder: gat
  activation: prelu
  in_drop: 0.2
  attn_drop: 0.1
  linear_prob: True
  loss_fn: sce
  drop_edge_rate: 0.0
  optimizer: adam
  replace_rate: 0.1
  alpha_l: 1 # or 3
  scheduler: True
pubmed:
  lr: 0.001
  lr_f: 0.01
  num_hidden: 1024
  num_heads: 4
  num_layers: 2
  weight_decay: 5e-6
  weight_decay_f: 1e-4
  max_epoch: 1000
  max_epoch_f: 300
  mask_rate: 0.75
  N_coms: 2
  use_mlp: True
  combine_type: concat
  encoder: gat
  decoder: gat
  activation: prelu
  in_drop: 0.2
  attn_drop: 0.1
  linear_prob: True
  loss_fn: sce
  drop_edge_rate: 0.0
  optimizer: adam
  replace_rate: 0.0
  alpha_l: 3
  scheduler: True
ppi:
  lr: 0.0001 #
  lr_f: 0.005
  save_model: True
  num_hidden: 1024
  num_heads: 4
  N_coms: 2
  use_mlp: False
  combine_type: concat
  weight_decay: 0
  weight_decay_f: 0
  max_epoch: 1000
  max_epoch_f: 2000
  mask_rate: 0.5
  num_layers: 3
  encoder: gat
  decoder: gat
  activation: prelu
  in_drop: 0.2
  loss_fn: sce
  optimizer: adam
  replace_rate: 0.1 # 0.1 for 256*4, else 0. 
  drop_edge_rate: 0.0
  alpha_l: 3
  norm: layernorm
  residual: True
  scheduler: True
  linear_prob: True

